### ISSUE TITLE
ImportError: No module named katello

### ISSUE THREAD

**Issue by stcoyle** [nicolas-r/katello-centos-errata-import#6]
Hello!

when i run the centos-errata-katello-importer.py script i am receiving the following error:

Traceback (most recent call last):
  File "./centos-errata-katello-importer.py", line 20, in <module>
    from katello.katello import katello
ImportError: No module named katello

however when i look in ~/katello-centos-errata-import/modules  the katello on is sitting there. is there something that i am missing? 

thanks!

**Comment by nicolas-r** [comment]
Hello

I just try to run it from a fresh git clone and it works fine for me
./centos-errata-katello-importer.py

Traceback (most recent call last):
  File "./centos-errata-katello-importer.py", line 47, in <module>
    with open("config.yaml", 'r') as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'

The error is normal because I don't create the config file but it finds the module. I have tested it on MacOS with python 3.6.5 from homebrew

Which version of python are you using ? On which plateform ? Are you using a virtualenv or not ?

**Comment by stcoyle** [comment]
its not a virtual server, just a regular one running CentOS 7 and im using python 2.7.5.it finds the first module fine just not the katello one.

**Comment by nicolas-r** [comment]
Hi

I have tested with default Python 2.7.10 from Mac OS and this is working.

Maybe you have the same issue than the one described in #5
